AllCops:
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'


MethodLength:
  Max: 35

# Metrics
Metrics/AbcSize:
  Max: 20
Metrics/LineLength:
  Max: 160

# Style
Style/AsciiComments:
  Enabled: false
Style/ClassAndModuleChildren:
  EnforcedStyle: compact
Style/Documentation:
  Enabled: false
Style/RedundantSelf:
  Enabled: false
